# ============================================================
# Plik: app/src/main/graphql/com/example/tripapp2/queries/TripDetails.graphql
# ============================================================
query TripDetailsQuery($tripId: Int!) {
    tripDetails(tripId: $tripId) {
        categories {
            categoryId
            totalAmount
        }
        currency
        dateEnd
        dateStart
        description
        expenses {
            amount
            categoryId
            currency
            date
            description
            id
            payerNickname
            name
            payerId
            sharedWith {
                isSettlement
                participantId
                participantNickname
                splitValue {
                    amount
                    currency
                    isMainCurrency
                }
            }
            totalExpense {
                amount
                currency
                isMainCurrency
            }
        }
        id
        imOwner
        myCost {
            amount
            currency
            isMainCurrency
        }
        ownerId
        participants {
            accessCode
            id
            isActive
            isOwner
            isPlaceholder
            nickname
            totalExpenses {
                amount
                currency
                isMainCurrency
            }
        }
        settlement {
            relations {
                relatedId
                relatedName
                allRelatedAmount {
                    amount
                    currency
                    isMainCurrency
                }
                leftForSettled {
                    amount
                    currency
                    isMainCurrency
                }
                prepayment {
                    amountLeft {
                        amount
                        currency
                        isMainCurrency
                    }
                    history {
                        date
                        values {
                            amount
                            currency
                            isMainCurrency
                        }
                    }
                }
            }
        }
        title
        totalExpenses
    }
}